language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: IPro0sycUgzZNKZix51w2fM4Qeqe8lSym9O20hWXKTW72s9k142p7bzhFE1/QM8mJlbDfH0yIyRu95+8H5rCdFDVM9yNEMn4Fmxkl7MutN5OAzr6emGlrNXzC/mK2mSlAtVIPkXyObpCMP41Ku+RJPbF6HZG7PXAYaBu/sd5R/GdkCUBiiMVtE9kqk2BOoW2P6pHrksilBznoV6OSvyWzEITT4ripqKUJ5Yfy5Di5R3rulqFG69CNy7+rNpuPwdPfJ08ff35sRGlN0N6E7hgzYZmv897tqA2W9HJj7zBSBqd7So5JxwFJipBSzIsWkbAJPXs5oVISr9x3n5x280S547z0hLrIFK8jickfGColcevgud5UgoKBQMipreBTzB8pUeEXT+6LKmApO2W7PhfKA87IH0LNR8F2lVDvYuvYv2Jq94wBQv4+fBvp/Bq64hy4fL9lxx8z5ux0Me3SwliXpsATkiW9TSH8jL/BKo3uu54Q9DnEQOoGhbBq2miZEXr8M9EqeX6fbuylu2qQ1Xa/Vw1CoJRagiJtwr8+O8HdwSKwwcqvnislEHJJ5JlOWqC1r9jQvr8i3O8Tb80YLkpGQfb+45F8WgViMM+BowtE5BQTbX3tcwxvl/1TiXU53SyRXvQh+jtfDPnhWZ8KX7btMJg4R2x8EWsjEzEytVy0Yc=
  app: fast-citadel-48845
  on:
    repo: mee213/node-capstone
branches:
  only:
  - master


